library(knitr)
library(rvest)
library(gsubfn)
library(tidyr)
library(tmap)
library(shiny)
library(readr)
library(dplyr)
library(tibble)
library(stringr)
library(tidyverse)
library(xml2)
library(ggplot2)
library(plotly)
library(sp)
library(rgdal)
library(plotrix)
library(rgeos)
library(raster)
library(tmap)
library(hrbrthemes)
library(viridis)
library(proto)
library(GGally)


options(gsubfn.engine="R")

# Uvozimo funkcije za pobiranje in uvoz zemljevida.
source("lib/uvozi.zemljevid.r", encoding="UTF-8")
